nla-deploy.sh

The issue was related to some files of the mail gem having "640" permissions instead of "644".
```
-rw-r-----.  1 root root 2.2K Dec  9 10:06 fields.rb
-rw-r-----.  1 root root 3.8K Dec  9 10:06 indifferent_hash.rb
```
Even though the permissions on delong are the same, somehow, the application can't load them on deshort.
This workaround just changes the permissions on the "vendor/bundle" directory and it's contents to allow puma to load the gems.

fix: fix permissions on vendor/bundle dir at deployment

---

app/assets/stylesheets/nla/_search-results.scss
app/components/blacklight/document/thumbnail_component.html.erb
app/components/blacklight/document_component.html.erb
app/components/blacklight/document_component.rb
app/components/blacklight/document_metadata_component.html.erb
app/components/blacklight/metadata_field_component.html.erb
app/components/blacklight/metadata_field_component.rb
app/components/blacklight/metadata_field_layout_component.html.erb
app/components/blacklight/metadata_field_layout_component.rb
app/presenters/nla_thumbnail_presenter.rb
app/views/catalog/_index_header.html.erb
spec/presenters/nla_thumbnail_presenter_spec.rb

Update the markup to use core bootstrap markup/layout properties rather than CSS floats. This does impact the display of the image on detail record pages

BLAC-168 - search results metadata layout to use bootstrap markup

---

app/controllers/catalog_controller.rb
app/helpers/field_helper.rb
spec/helpers/field_helper_spec.rb

Let me actually fix the problem. 😛 
Refactors the `catalogue_search_list` helper to accept a separate array of values for the search term than the displayed value.

fix: fix author search link [BLAC-15]

---

app/controllers/catalog_controller.rb

This change will allow the search to return books even when the author in the search term is not the primary author.

fix: use "author_search_tsim" as the author search field [BLAC-15]

---

Gemfile.lock
app/views/advanced/_advanced_search_submit_btns.html.erb

Didn't realise that the `<div>` that included the sort drop down on the Advanced Search page included a hidden text field. Removing this caused the Advanced Search to ignore the search term and redirect to the home page instead of performing a search.
I've restored the hidden text field and upgraded dependencies.

fix: restore hidden field removed from advanced search page [BLAC-208]

---

app/controllers/catalog_controller.rb

The default pf field is the all values fields which mucked up the relevance ranking (the issue with call number MS 1 logged in the issues list was caused by this)

BLAC-230 Include phrase slop to search fields to improve relevance results

---

app/controllers/catalog_controller.rb
app/models/search_builder.rb

Use edismax parser and push title matches to top of all fields search. Had to add the title booster expression to the BL config, and add the bf to solr search as part of the search builder, else if the q param isn't there Solr goes all NPE.

BLAC-262 Improve relevance ranking

---

app/components/catalogue_record_actions_component.rb
spec/components/catalogue_record_actions_component_spec.rb

Copy + paste mistake. Should use the `href` value, rather than checking if it includes "nla.gov.au".

fix: fix View online URL [BLAC-273]

---

app/helpers/application_helper.rb

Sidebar should only be shown on catalogue pages, but because the `root_url` is also the catalogue controller index route, it is also accessible without having `/catalogue` in the URL path.
I hate routes!

fix: missing sidebar

---

app/controllers/static_pages_controller.rb
app/helpers/application_helper.rb
app/helpers/layout_helper.rb
app/helpers/single_search_helper.rb
app/views/layouts/blacklight.html.erb
app/views/layouts/blacklight/base.html.erb
app/views/shared/_header_navbar.html.erb
app/views/static_pages/home.html.erb
config/routes.rb
spec/helpers/single_search_helper_spec.rb
spec/requests/static_pages_spec.rb

Creates a new controller for static pages and updates the root path/URL to point to a static home page instead of the catalogue index.
This makes it easier to logically target the home page without having to check if the current path is also the catalogue index.

feat!: create separate home page from catalog [BLAC-286]

---

.simplecov
app/components/catalogue_record_actions_component.html.erb
app/components/copies_direct_order_form_component.html.erb
app/components/copies_direct_order_form_component.rb
app/controllers/catalog_controller.rb
app/views/catalog/_copies_direct_form.html.erb
spec/components/copies_direct_order_form_component_spec.rb
spec/helpers/layout_helper_spec.rb

Moves Copies Direct form to a component separate from the document actions component, so it can be included in the document/show view all the time.
Also added a spec to verify the behavior of the `LayoutHelper#main_content_classes`.

fix: fixes broken copies direct link in copyright [BLAC-291]

---

app/helpers/blacklight_helper.rb
spec/helpers/blacklight_helper_spec.rb

The `#content_tag` performs encoding of apostrophes and special characters by default when constructing a tag, so it needs to be escaped first, otherwise it will just return the HTML entity as regular text.
`#render_document_heading` is a deprecated method, so I really don't like changing it to fix this. In Blacklight 8, the document is rendered in a view component, so this will definitely have to be re-implemented in the future.

fix: correctly encode apostrophe and other HTML entities in title

---

app/helpers/url_helper.rb

Overrides the `Blacklight::UrlHelperBehavior#link_to_document` method to truncate the title on the search results index page.

feat: truncate titles to 175 characters on index search page

---

app/controllers/search_controller.rb
app/search_engines/bento_search/ebsco_eds_engine.rb
app/views/bento_search/_item_title.html.erb
spec/support/webmock.rb

Ripped out original Cornell code to make the response faster. Also truncate the linked titles to match the catalogue search results titles.

fix: EDS bento perf

---

app/helpers/application_helper.rb
app/views/catalog/_home_text.html.erb

The global message was missing from the home page after I restructured the application root route to not point to the catalogue search index page.

fix: display of global message on home page

---

app/views/request/create.html.erb
config/locales/en.yml
spec/helpers/request_helper_spec.rb
spec/requests/request_spec.rb

Putting some generic delivery information on the success page while waiting for feedback on implementation of BLAC-275

feat: delivery information

---

app/controllers/search_controller.rb
app/search_engines/bento_search/blacklight_engine.rb

When an error is raised in the bento search engine, it may return a nil value for `total_items`, so we need to check it and make sure to add 0 instead of try to convert to an integer.

fix: fix nil error

---

app/helpers/url_helper.rb
app/presenters/nla_thumbnail_presenter.rb
spec/presenters/nla_thumbnail_presenter_spec.rb

The image tag would get chopped off because of the truncation logic in `UrlHelper::link_to_document`.
The underlying reason was that the `NlaThumbnailPresenter` should not have been sending the image tag to the `#link_to_document` method in the first place.

fix: fixes linking of images on search results page [BLAC-318]

---

app/controllers/catalog_controller.rb

Noticed the subject search wasn't configured, so was just doing an all fields search when subject was selected. Also removed id field from pf/qf parameter for title search config since it doesn't make sense to be there

BLAC-323 Subject search not configured properly

---

app/components/blacklight/document/thumbnail_component.html.erb
app/services/catalogue_services_client.rb

Pushes the thumbnail cashing to a lower level from the page to the `CatalogueServicesClient`. This takes into account the different sizes between the catalogue search results and the catalogue record page.

refactor: move thumbnail cache from page to service

---

app/search_engines/bento_search/eds_api_engine.rb
spec/support/webmock.rb

This fixes the discrepancy in search results between searching via the EDS live site vs the EDS API gem.
**Cause:**
The gem is unable to parse the query string in the same way the EDS API is able to. According to the EDS API docs, the format `{booleanOperator},{fieldCode}:{term}` is valid. When passing this query string into the EDS API via the gem, it's unable to parse the `{booleanOperator}` and `{fieldCode}` parts of the query string into the appropriate `SearchCriteria` parameters for the request payload. 
See https://github.com/ebsco/edsapi-ruby/blob/6319460d9b76714db64784cfbce8d26b0fd9beba/lib/ebsco/eds/options.rb#L250.
Example search using the query string "AND,TI:hydrogen"
Request payload via edsapi-ruby:
```json
{
"SearchCriteria": {
"Queries": [
{
"Term": "AND,TI:hydrogen"
}
], …
```

fix: reformat query string for EDS API

---

app/views/search/index.html.erb
app/views/shared/_header_navbar.html.erb
app/views/static_pages/home.html.erb
config/locales/en.yml

Change the bento search and home page header to "Search" instead of "Catalogue".

fix: search page header

---

app/views/catalog/_home_text.html.erb

Sorry, nuking the content for this is a temporary solution that will force us & reader services to revisit content for this page. Will have to do another PR/Deploy once we've got it finalised.

BLAC-355: remove duplicate content  on catalogue specific  homepage

---

app/controllers/application_controller.rb

Each panel in the beto search results page is a separate get request that is rendered in a TurboFrame. this ensures that if a user logs in while they're viewing bento search results, they will not be redirected back to a single engine result, but to all the bento search results.

feat: ensure login from bento results redirects back to all search results

---

app/services/catalogue_services_client.rb
app/views/catalog/_thumbnail.html.erb
config/application.rb

Put thumbnails behind a feature flag that can be turned on and off. Also added a rescue block for the service method that retrieves thumbnails just in case.

fix: put thumbnails behind feature flag and add rescue to thumbnails

---

app/components/request_item_component.html.erb
app/views/request/new.html.erb
spec/files/catalogue_services/1414519.json
spec/files/catalogue_services/monograph.json
spec/files/catalogue_services/serial.json

Data Systems said we should use effectiveCallNumberLocation.callNumber rather than itemLevelCallNumber as they are not going to populate the callNumber at item level, this new field is added to the item response by Folio based on holding call number

BLAC-383 change callnumber display field

---

app/components/blacklight/document/thumbnail_component.html.erb
app/helpers/thumbnail_helper.rb
app/presenters/nla_thumbnail_presenter.rb
app/services/thumbnail_service.rb
app/views/catalog/_thumbnail.html.erb
spec/presenters/nla_thumbnail_presenter_spec.rb

Removing the TurboFrames implementation for now and rolling back to the StimulusJS implementation.
I can't seem to make Turbo stop caching the thumbnail frame when navigating back with the browser back button. The configuration options I've read through in the docs don't seem to be working. 😞

fix: load thumbnails in correct size based on view

---

Gemfile.lock
app/components/requests_table_component.html.erb
app/components/requests_table_component.rb
app/views/account/requests.html.erb
app/views/shared/_user_util_links.html.erb
config/locales/en.yml
config/routes.rb
spec/components/requests_table_component_spec.rb

Refactored to display a common message for each table when there are no requests of that type.
This includes the [fix in nla-blacklight_common](https://github.com/nla/nla-blacklight_common/pull/7) for staff request summary.

fix: display "no request" message for each type of request

---

app/controllers/application_controller.rb

Adds `request#index` to the list of ignored redirect actions so user will not redirect back to it on login.

fix: add request#index action to ignored redirects locations

---

config/routes.rb
spec/requests/vufind_redirect_spec.rb

This change will redirect the following VuFind URL segments to the corresponding Blacklight URL segments:
1.  `/Record/[id]` ---> `/catalog/[id]`
e.g. Given the VuFind URL `https://catalogue.nla.gov.au/Record/3579167`, it will redirect to `https://catalogue.nla.gov.au/catalog/3579167`. 
Any query string values after `/Record/[id]` are dropped as they are more than likely not compatible with Blacklight.
2.  `/Record/[id]/Offsite?[query-string]` ---> `/catalog/[id]/Offsite?[query-string]`

feat: redirect old VuFind URLs

---

.env.test
app/models/solr_document.rb
spec/models/solr_document_spec.rb

Having spaces in the LCCN (which were then encoded as `+` symbols in the URL) were causing a 404 to be returned from the catalogue-service.
I've made sure all whitespace are removed for ISBNs and LCCNs.

fix: thumbnail 404

---

Gemfile
Gemfile.lock
app/components/request_item_component.rb
app/controllers/account_controller.rb
app/controllers/application_controller.rb
app/controllers/request_controller.rb
app/controllers/search_controller.rb
app/helpers/application_helper.rb
app/helpers/thumbnail_helper.rb
app/services/catalogue_services_client.rb
app/views/account/requests.html.erb
app/views/request/new.html.erb
app/views/request/success.html.erb
config/initializers/rack-mini-profiler.rb

Remove the authentication code from the catalogue services client code and some other bits that are no longer relevant.
Have added rack-mini profiler and the ability to turn it on in prod if needed.

feat: clean up code and add enable profiling for prod

---

app/assets/stylesheets/nla/_record.scss
app/assets/stylesheets/nla/components/_bento-search.scss
app/views/bento_search/_item_title.html.erb
config/application.rb

Removes underlines and numbering from title links.
Also added some code to silence the deprecation warnings in staging/prod so they don't clutter up the logs.

feat: restyle title links and silence deprecations

---

.rubocop.yml
Gemfile
Gemfile.lock
app/helpers/application_helper.rb
app/helpers/thumbnail_helper.rb
app/models/request_detail.rb
app/services/thumbnail_service.rb
config/application.rb
config/database.yml
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
config/initializers/rack-mini-profiler.rb
config/puma.rb
config/routes.rb

- Add `puma_worker_killer` for rolling phased restarts of Puma.
- Remove cache writes to Redis
- Silence deprecation warnings in devel also
- Make prod database timeouts the default in all environments
- Remove `rails_performance` to reduce Redis usage

fix: reduce memory usage

---

app/assets/stylesheets/nla/_facets.scss

Sorry, Just one very small fix for some bright green text showing up in the year chart modal. I'm also seeing an "=" sign just in the Catalogue version. Wasn't appearing in Finding aids, but I couldn't work out where it was coming from.

BLAC-464: change green text in modal to grey

---

app/helpers/single_search_helper.rb
app/models/search_link.rb
spec/helpers/single_search_helper_spec.rb

There are some 856 u fields which are just text, like a note or the link text. When the URL is parsed it fails so this just catches the exception and essentially ignores the value. The actual problem was in the google url builder but I have added the error handling wherever the URL might be parsed by Addressable.
It was also a bit weird, a url value of"this is not a url" doesn't throw an exception, but "Full text available from Masterfile Premier: 01/01/1990 to present" did, so probably only a limited number will fail anyway, I guess it's the colon.

BLAC-528 Stop record view crashing with bad URL values

---

config/environments/production.rb
config/environments/staging.rb

Tested with current code in nla-blacklight_common that forces the cookie to be secure in production: https://github.com/nla/nla-blacklight_common/blob/669fd6d2ea38b661f68b03cfb240c018374e5e80/config/initializers/session_store.rb#L1
Also added "localhost" to the allowed hosts in staging and prod configs, in case something needs to access it from localhost. Most likely not.

fix: turn off force_ssl and add "localhost" to hosts in staging/prod

---

app/components/request_table_row_component.html.erb
spec/components/request_table_row_component_spec.rb

Reverts changes for BLAC-523 to add requests info to request summary notes.

revert: revert display of year, enumeration and chronology

---

app/controllers/catalog_controller.rb
app/models/eresources.rb
app/models/eresources_stats.rb
app/services/catalogue_services_client.rb
app/services/eresources_config_service.rb
config/initializers/mini_profiler.rb
spec/models/eresources_spec.rb
spec/requests/offsite_redirect_spec.rb
spec/services/catalogue_services_client_spec.rb
spec/services/eresources_config_service_spec.rb
spec/support/webmock.rb

Post stats to catalogue-services for reporting.
Also configures rack-miniprofiler to store stats into Redis and refactors the fetching of the eResources config JSON into a separate service.

feat: eResources stats

---

app/search_engines/bento_search/eds_api_engine.rb
spec/support/webmock.rb
spec/system/bento_search_spec.rb

Matches the default search configuration in eResources, so the number of results will match when clicking through to eResources from the bento search.

fix: change limiters and expanders params for EDS API

---

Gemfile.lock

Changes are feature flagged behind `KC_PATRON_REALM` environment variable, so should display and function using UserReg until Keycloak patron realm configuration is configured.

chore: pull in patron Keycloak login changes

---

Gemfile
Gemfile.lock
app/models/request_detail.rb
app/services/catalogue_services_client.rb
app/views/account/request_details.html.erb
config/locales/en.yml
spec/components/request_table_row_component_spec.rb
spec/files/account/request_summary.json
spec/files/account/single_request.json
spec/files/account/single_request_with_cancellation.json
spec/services/catalogue_services_client_spec.rb
spec/support/webmock.rb
spec/system/request_summary_spec.rb

Changes the label and table heading for the request details date to "Date" and removes the seconds from the timestamp.
Changes also applied to request summary and request details modal.

feat: remove seconds from timestamp and change label to "Date"

---

app/components/user_details_field_component.html.erb
app/services/catalogue_services_client.rb
app/views/account/profile/_form.html.erb

Increased the max lenght accepted by the email form field to the maximum accepted by Keycloak. Also added the `text-break` class to the value column on the profile details page to void overlapping the edit links.

fix: increase email field length to max length in Keycloak

---

Gemfile.lock
app/controllers/application_controller.rb
app/views/static_pages/home.html.erb

Tell the browser not to cache any pages via the 'Cache-Control', 'Pragma' and 'Expires' headers. Of course the user can still change the browser settings to ignore these headers if they want to.

fix: set headers to not cache any pages

---

app/controllers/application_controller.rb
app/javascript/blacklight_custom.js
app/javascript/controllers/form_validation_controller.js
config/brakeman.ignore

The warnings are coming from Brakeman and not Rubocop. 
Based on Brakeman's documentation, these are likely false positives. 
See:
- https://brakemanscanner.org/docs/warning_types/redirect/ 
- https://brakemanscanner.org/docs/warning_types/dynamic_render_paths/
These hadn't raised warnings before the upgrade and with no changes to this code as well, I've decided to add them to the ignore file.
Additionally, I've put in a global rescue to redirect to the home page if there ever was an `ActionController::Redirecting::UnsafeRedirectError` raised.
I also cleaned up some left over JavaScript debugging loggers.

fix: linter warnings

---

Gemfile
Gemfile.lock
app/controllers/catalog_controller.rb
app/models/request_detail.rb
app/services/related_records_service.rb

Depends on https://github.com/nla/nla-blacklight_common/pull/59
Pulls in changes from common lib and configures Blacklight to use /select instead of /get for single document search and pass some extra default params to avoid returning the response header, spellcheck and facets.

fix!(solr): single document search

---

app/models/eresources.rb
spec/models/eresources_spec.rb

When an eResources JSON record's `urlstem` contains a trailing slash, it will not match root URLs that don't have this slash and Blacklight will display the record not found page.
e.g. The url "https://example.com" does not start with the `urlstem` "https://example.com/", but they're effectively the same root URL.
To avoid this, this change adds an additional check to see if the url starts with the `urlstem` without the trailing slash.

fix: remove trailing slash from urlstem when matching root url

---

.env.development
.env.staging
.env.test
Gemfile.lock
app/helpers/request_item_helper.rb
app/views/shared/_user_util_links.html.erb
spec/components/catalogue_record_actions_component_spec.rb
spec/components/request_item_component_spec.rb
spec/features/account_spec.rb
spec/system/nav_actions_spec.rb

Disables login during FOLIO updates. Also refactored the previous changes to disable requesting to all be under the same flag.

feat: disable login during FOLIO updates

---

app/controllers/account_controller.rb
app/models/user_details.rb
spec/files/profile/user_details.json
spec/system/profile_spec.rb

I introduced an error with editing the user attributes when I added the email 2FA attribute to the `UserDetails` model that caused the object not to be initialised correctly when passed a hash of attributes.

fix: fix editing of user details

---

.env.development
.env.staging
.env.test

Reverts nla/nla-blacklight#1161
having the env contain the url seems to break automated testing jobs.

Revert "Update env GLOBAL_MESSAGE_URL"
