app/components/blacklight/document/more_like_this_component.html.erb, config/locales/blacklight.en.yml
Update to match production Catalogue.
=> feat: changes title of More Like This component to Similar Items

app/components/blacklight/document/thumbnail_component.html.erb, app/presenters/nla_thumbnail_presenter.rb, spec/presenters/nla_thumbnail_presenter_spec.rb
Feels like a really really really ugly way of doing it - sure there must be a much better way
=> BLAC-184: Resize image on record page

app/controllers/catalog_controller.rb
temporarily remove the links until further analysis has been done
=> fix: remove links from former/later title and has supplement/to [BLAC-201]

app/views/shared/_user_util_links.html.erb
This will have to get pulled out later once the staff beta is over
=> BLAC-209: Add staff beta feedback link

app/assets/stylesheets/nla/_homepage.scss, app/components/blacklight/response/facet_group_component.html.erb, app/helpers/blacklight/layout_helper_behavior.rb, app/views/catalog/_sort_and_per_page.html.erb
Just a small layout fix from one of the bits of feedback
=> BLAC-222: change tablet portrait view to 2 columns

Gemfile.lock, app/assets/stylesheets/nla/_search-results.scss, app/components/blacklight/start_over_button_component.rb, app/components/blacklight/system/dropdown_component.html.erb, app/components/blacklight/system/dropdown_component.rb
There's still work to do on "Start over" button - that can be another ticket
=> BLAC-224: Restyle applied limits on search results page

app/helpers/blacklight/blacklight_helper_behavior.rb
Minor style fix for "massive text" headings
=> BLAC-261 resize title on record page

app/assets/stylesheets/nla/components/_catalogue-record-actions.scss, app/components/catalogue_record_actions_component.html.erb
Just a really minor stying fix for the buttons
=> BLAC-273: Style button actions

.github/workflows/release.yml, app/controllers/search_controller.rb, app/views/single_search/index.html.erb, spec/support/webmock.rb
Removed EDS and quick refactor to remove threading as well to make everything as stupidly simple as possible.
=> fix: remove EDS API search from bento search to improve perf [BLAC-293]

.github/workflows/verify.yml, .simplecov, app/controllers/search_controller.rb, config/application.rb
The text should say "view x catalogue", but it says "view x from finding aids".
=> fix: catalogue bento results button label

Gemfile.lock
=> chore: integrate renaming of staff shared login

app/controllers/catalog_controller.rb, app/models/search_builder.rb, solr/conf/schema.xml
change boosting and default search fields, remove title term frequency boost as long title favoured over expected ranking, apply same schema change as solr-trove
=> BLAC-321 improve title search rankings

app/assets/stylesheets/nla/components/_bento-search.scss, app/views/single_search/_pane_results.html.erb
After talking with Simon we thought these needed a little more clarity. Simple restyle
=> BLAC-268: change styling of bento headings

app/controllers/catalog_controller.rb
Apply minor boost to id matches so bibid match appears above amicus id search results
=> BLAC-335 Blacklight - Relevance on Bib ID search

app/assets/stylesheets/nla/_header.scss, app/controllers/catalog_controller.rb, app/views/blacklight/nav/_bookmark.html.erb, app/views/shared/_user_util_links.html.erb, config/locales/blacklight.en.yml
- Direct links to each search target
- Move "User" functions to drop down menu
=> BLAC-333: Restyle primary navigation

Gemfile, Gemfile.lock, app/components/request_item_component.html.erb, app/components/request_item_component.rb, app/controllers/request_controller.rb, app/services/catalogue_services_client.rb, app/views/errors/internal_server.html.erb, app/views/errors/not_found.html.erb, app/views/errors/unprocessable.html.erb, spec/requests/request_spec.rb
Display an error if there is an issue fetching holdings from catalogue-services and refactor how the request controller redirects to the error pages if something goes wrong during the process of requesting an item.
=> refactor: requesting errors

app/assets/stylesheets/nla/_record.scss, app/components/citation_component.html.erb
Sorry, should have fleshed out the original ticket with these
=> BLAC-279: minor accessibility improvements to PI citation

app/components/request_item_component.html.erb, app/views/request/_form.html.erb, app/views/request/create.html.erb, app/views/request/new.html.erb
Just minor UI tweaks for request
=> BLAC-345: UI align elements in request

app/assets/stylesheets/nla/_skeleton.scss, app/components/request_item_component.html.erb, app/components/request_item_component.rb, app/controllers/request_controller.rb, app/views/catalog/_request_item.html.erb, app/views/request/_form.html.erb, app/views/request/index.html.erb, app/views/request/new.html.erb, app/views/request/show.html.erb, app/views/request/success.html.erb, config/routes.rb, spec/components/request_item_component_spec.rb, spec/requests/request_spec.rb
Defer loading the holdings until the section scrolls into view or the user actually wants to request the item.
=> feat: lazy load requesting

app/assets/stylesheets/nla/components/_request_summary.scss, app/controllers/account_controller.rb, app/views/account/requests.html.erb, app/views/shared/_user_util_links.html.erb, config/locales/en.yml, config/routes.rb, spec/requests/account_spec.rb
Adds "Requests" to header navigation dropdown. Also added a placeholder page for the user's request summary.
=> feat: add Requests menu link and dummy page

Gemfile.lock, app/components/request_table_row_component.html.erb, app/components/request_table_row_component.rb, app/components/requests_table_component.html.erb, app/components/requests_table_component.rb, app/controllers/account_controller.rb, app/helpers/application_helper.rb, app/models/request_detail.rb, app/services/catalogue_services_client.rb, app/views/account/requests.html.erb, bin/setup, spec/components/copyright_status_component_spec.rb, spec/components/request_item_component_spec.rb, spec/components/request_table_row_component_spec.rb, spec/components/requests_table_component_spec.rb, spec/files/account/record_search.json, spec/files/account/request_summary.json, spec/files/account/single_request.json, spec/helpers/field_helper_spec.rb, spec/models/solr_document_spec.rb, spec/requests/account_spec.rb, spec/services/catalogue_services_client_spec.rb, spec/support/webmock.rb, spec/system/document_exports_spec.rb
First cut of user request summary page.
=> fix: implement requests summary for user

app/components/catalogue_record_actions_component.rb, app/components/request_item_component.rb, app/helpers/request_item_helper.rb, app/views/catalog/_request_item.html.erb
Don't display requesting for electronic or internet resources.
=> fix: electronic resources

app/components/catalogue_record_actions_component.rb, app/models/eresources.rb, app/models/solr_document.rb
Take into accoun the rule where there won't be a format if the only value is "Online".
Also verifies the `eresources.cfg` is valid JSON before caching it.
=> fix: format check

app/components/blacklight/document/thumbnail_component.html.erb, app/helpers/thumbnail_helper.rb, app/presenters/nla_thumbnail_presenter.rb, app/services/thumbnail_service.rb, app/views/catalog/_thumbnail.html.erb, spec/presenters/nla_thumbnail_presenter_spec.rb
Same change as https://github.com/nla/nla-blacklight/pull/579 for the release branch.
=> fix: thumbnail size

app/assets/stylesheets/nla/_header.scss, app/controllers/catalog_controller.rb, app/views/shared/nav/_ask_a_librarian.html.erb, app/views/shared/nav/_help.html.erb, config/locales/blacklight.en.yml
Add Ask a librarian and help to header nav
=> BLAC-333: Add links to header

app/controllers/account_controller.rb, app/controllers/catalog_controller.rb, app/controllers/request_controller.rb, app/services/catalogue_services_client.rb, app/views/account/requests.html.erb, app/views/request/new.html.erb, app/views/request/success.html.erb, config/locales/en.yml, spec/features/account_spec.rb, spec/features/requests_spec.rb, spec/requests/account_spec.rb, spec/services/catalogue_services_client_spec.rb, spec/support/webmock.rb
=> feat: display request limit message

Gemfile.lock, app/assets/stylesheets/nla/_header.scss, app/views/shared/_user_util_links.html.erb, app/views/shared/nav/_catalogue.html.erb, app/views/shared/nav/_new_search.html.erb
Pulls in helper from `nla-blacklight_common` and adds active link style to navbar.
=> feat: add active link to navbar

app/components/request_limit_message_component.html.erb, app/components/request_limit_message_component.rb, app/controllers/account_controller.rb, app/controllers/request_controller.rb, app/views/account/requests.html.erb, app/views/request/new.html.erb, app/views/request/success.html.erb, config/catalogue.yml, config/locales/en.yml, spec/components/request_limit_message_component_spec.rb
Resolves BLAC-435, BLAC-436, BLAC-437, BLAC-438.
=> feat: request limit error rewording

app/components/request_item_component.rb
Display error message instead of "Content missing".
=> fix: display service error

app/views/account/requests.html.erb
=> feat: request summary order

app/assets/stylesheets/nla/components/_bento-search.scss, app/views/search/_pane_results.html.erb, config/initializers/bento_search.rb
Is it possible to get this deployed to devel on Monday morning? Reader services are creating help documentation and are taking screen shots. Thanks
=> BLAC-455: Rename eResources bento and update styles

app/components/request_item_component.html.erb, app/components/request_item_component.rb, app/helpers/request_helper.rb, app/views/request/new.html.erb, config/locales/en.yml, spec/files/catalogue_services/1414519.json, spec/files/catalogue_services/monograph.json, spec/files/catalogue_services/serial.json, spec/files/catalogue_services/serial_manuscript.json, spec/helpers/request_helper_spec.rb
Display "in use" items, status and display disabled "In use" button.
=> "in use" status and display

app/assets/stylesheets/nla/_nla-custom-bootstrap.scss, app/assets/stylesheets/nla/_record.scss
=> BLAC-468: colour contrast for metadata labels

app/assets/stylesheets/nla/_nla-custom-bootstrap.scss
sorry, needed to modify a colour to match finding aids
=> BLAC-468: Colour contrast

Gemfile, Gemfile.lock, app/views/shared/nav/_help.html.erb
Sorry - last minute change from Reader Services
=> BLAC-483: Update URL for help

Gemfile, Gemfile.lock, nla-deploy.sh
Fixed caching in the Devel env and added the call to clear the Redis cache on deploy.
=> chore: prepare Sprint 6

app/views/request/_manuscripts_form.html.erb, app/views/request/_maps_form.html.erb, app/views/request/_serials_form.html.erb
fix: correct enumeration mapping
=> fix: merge hotfix changes from main

app/views/shared/_header_navbar.html.erb
BLAC-515: Show login on tablet
=> chore: merge changes from main

app/controllers/catalog_controller.rb, app/models/eresources.rb, app/models/eresources_stats.rb, app/services/catalogue_services_client.rb, app/services/eresources_config_service.rb, config/initializers/mini_profiler.rb, spec/models/eresources_spec.rb, spec/requests/offsite_redirect_spec.rb, spec/services/catalogue_services_client_spec.rb, spec/services/eresources_config_service_spec.rb, spec/support/webmock.rb
Reverts nla/nla-blacklight#724
=> Revert "Revert "feat: eResources stats""

app/controllers/catalog_controller.rb
This is the updated controller config for search, which combined with some new index fields and schema/config changes, resolves a lot of the issues related to search
=> BLAC-573 Update Blacklight search configuration

app/components/user_details_field_component.html.erb, app/components/user_details_field_component.rb, app/controllers/account_controller.rb, app/models/user_details.rb, app/services/catalogue_services_client.rb, app/views/account/settings.html.erb, app/views/account/settings_edit.html.erb, config/locales/en.yml, config/routes.rb, spec/components/user_details_field_component_spec.rb, spec/files/account/user_folio_details.json, spec/requests/account_spec.rb, spec/services/catalogue_services_client_spec.rb, spec/simplecov_helper.rb
Clicking on link will display edit form, but it's not really tested to perform updates correctly yet.
=> feat: view user details

Gemfile, Gemfile.lock, app/assets/stylesheets/nla/_forms.scss, app/assets/stylesheets/nla/_nla-blacklight.scss, app/assets/stylesheets/nla/components/_user-details-field-component.scss, app/components/user_details_field_component.html.erb, app/components/user_details_field_component.rb, app/controllers/account_controller.rb, app/helpers/url_helper.rb, app/models/user_details.rb, app/services/catalogue_services_client.rb, app/views/account/settings.html.erb, app/views/account/settings/_editable_attribute.html.erb, app/views/account/settings/_form.html.erb, app/views/account/settings_edit.html.erb, bin/ci, config/application.rb, config/locales/en.yml, config/routes.rb, spec/components/user_details_field_component_spec.rb, spec/services/catalogue_services_client_spec.rb, spec/system/support/precompile_assets.rb
Uses `email_validator` gem to validate email format. It's fairly loose, checking if there is an "@" with text before and a fully qualified domain after, without whitespace.
=> feat: allow logged in users to change their email

Gemfile.lock, app/models/user_details.rb, app/views/account/settings/_form.html.erb
Also changed email format validation to only trigger if an email address is present.
=> fix: change maxlength of email input field

app/components/user_details_field_component.html.erb, app/components/user_details_field_component.rb, app/views/account/profile.html.erb
Also refactored to move edit link to third column instead.
=> fix: staff password is not editable

public/robots.txt
Paul provided a list of pages which to block indexing for
=> BLAC-616 add disallows for pages to robots.txt

app/services/nla/citations/wikimedia_citation_service.rb, spec/services/nla/citations/wikimedia_citation_service_spec.rb
do tests for 'build_via' and 'build_access_date' seem redundant?
=> BLAC-623 wikipedia citations

package.json, yarn.lock
Reverts nla/nla-blacklight#862
=> revert: "chore(deps): bump postcss-cli from 10.1.0 to 11.0.0"

app/components/requests_table_component.html.erb
Fixes the way the page displays the tables and the request total badges.
=> fix: replace deprecated Bootstrap styles

app/components/blacklight/start_over_button_component.rb
Had to add one more fix to the ticket. Add spacing to “New Catalogue search” button
=> BLAC-631: Bootstrap spacing

app/views/request_item/_holding.html.erb, spec/components/request_item_component_spec.rb
Update availability status to specify if item is available or not for loan based on Folio requestable status.
=> BLAC-522: Show FOLIO requestable status

Gemfile.lock, app/views/request/new.html.erb, config/locales/en.yml, spec/features/requests_spec.rb
=> BLAC-679: 7-day hold message

app/models/user_details.rb
Enable email 2FA again now that the last release has been deployed to allow testing to resume.
=> revert: revert disabling of email 2FA

.gitignore, spec/components/explore_component_spec.rb
These are the changes you're looking for...
=> test: test that bookshop link does not display

Gemfile, Gemfile.lock
point nla-blacklight_common back to main branch
=> chore: point deps back to main

Gemfile, Gemfile.lock, config/application.rb
give up on release-please for now, just get a release sorted and look into it later...
=> chore: prepare release

Gemfile, Gemfile.lock
change BL common target back to main
=> chore: post release

package.json, yarn.lock
Reverts nla/nla-blacklight#1068
=> Revert "chore(deps): bump blacklight-frontend from 8.3.0 to 8.4.0"

Gemfile, Gemfile.lock
=> post release

.env.development, .env.staging, .env.test, app/components/blacklight/top_navbar_component.html.erb, app/components/copyright_status_component.html.erb, app/controllers/catalog_controller.rb, app/helpers/request_helper.rb, app/views/request/_manuscripts_form.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_user_util_links.html.erb, app/views/shared/nav/_ask_a_librarian.html.erb, app/views/shared/nav/_help.html.erb, app/views/static_pages/home.html.erb, config/catalogue.yml, config/locales/en.yml
Now that the final production site for library.gov.au is live (behind the password), can update all URL's to their final versions.
=> CTPL-265: Update links to new pages at library.gov.au

app/controllers/request_controller.rb, spec/features/requests_spec.rb
Temporarily disable picture requesting form.
=> CTPL-199: Disable picture requesting

.env.development, .env.staging, .env.test
To merge afternoon of Tues Dec 10.
=> Update env GLOBAL_MESSAGE_URL

app/helpers/single_search_helper.rb
=> CTPL-313: fix bento catalogue link

app/components/blacklight/advanced_search_form_component.html.erb
Part of Vision Australia accessibility fixes
=> CTPL-283: Add JS focus to start over button

app/views/static_pages/home.html.erb
Part of Vision Australia accessibility fixes
=> CTPL-282: Blank alt text for images on homepage

app/presenters/nla_thumbnail_presenter.rb
Part of Vision Australia accessibility fixes
=> CTPL-283: Blank alt text for thumbnail/collection image

app/javascript/blacklight_custom.js, app/views/catalog/_request_item.html.erb
Part of Vision Australia fixes
=> CTPL-300: Set focus on request section when button click

app/assets/stylesheets/nla/_alert.scss, app/components/blacklight/system/flash_message_component.html.erb
Part of Vision Australia fixes
=> CTPL-289: Make close button on alert keyboard accessible

app/javascript/blacklight_custom.js, app/views/search/_pane_results.html.erb
Part of Vision Australia accessibility fixes
=> CTPL-299: Bento search results anchor links don't reassign focus

Gemfile.lock
=> bump nla-blacklight_common

app/assets/stylesheets/nla/_advanced-search.scss, app/assets/stylesheets/nla/_dark-mode.scss
Fixing issue that was raised during testing on CTPL-301
=> CTPL-301: Update styling of facets on advanced search to complement regular facet styles

app/assets/stylesheets/nla/_dark-mode.scss
Sorry, needed 1 more fix for this
=> CTPL-301: Update styling of form fields on advanced search in dark mode

app/views/shared/_footer.html.erb
so it isn't read out by screen readers
=> CTPL-307: Remove book curl image in footer from accessibility tree 

app/components/blacklight/search_bar_component.html.erb, app/components/blacklight/search_bar_component.rb, app/components/blacklight/search_navbar_component.html.erb, app/views/search/_home_search_form.html.erb, app/views/search/_search_form.html.erb
=> CTPL-327: Improve search form for screen readers
